### ISSUE TITLE
`grav-id` parameter does not work

### ISSUE THREAD

**Issue by marshmn** [finanalyst/grav-plugin-datatables#3]
The `grav-id` parameter is supposed to allow the setting of an id on the rendered table, however this does not appear to work.

**Comment by finanalyst** [comment]
Hi Matt,
Thanks for your help on another plugin. Can you give me an example that does not work. I have used the id for a table.

**Comment by marshmn** [comment]
Sorry for taking so long to reply... I've only just returned to this...

Here is an example:

```
[datatables grav-id=foo]
| Header 1 | Header 2 |
|----------|----------|
| ABC      | DEF      |
[/datatables]
```
And here is the HTML produced:
![Selection_056](https://user-images.githubusercontent.com/4307033/57981664-4ec50900-7a32-11e9-8ca5-c2749b695170.png)
